# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField(default=1, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('health', models.IntegerField(default=30, max_length=2)),
                ('mana_cristals', models.IntegerField(default=1, max_length=2)),
                ('current_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Card')),
                ('health', models.IntegerField(default=1, max_length=2)),
                ('strengh', models.IntegerField(default=1, max_length=2)),
            ],
            bases=('app.card',),
        ),
        migrations.CreateModel(
            name='SpellCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Card')),
                ('effect', models.CharField(max_length=100)),
            ],
            bases=('app.card',),
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Card'),
        ),
    ]
