# Generated by Django 2.0 on 2017-12-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField(default=1)),
                ('picture', models.CharField(default=None, max_length=255, null=True)),
                ('health', models.IntegerField(default=None, null=True)),
                ('strengh', models.IntegerField(default=None, null=True)),
                ('effect', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Monster', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cards', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('health', models.IntegerField(default=30)),
                ('mana_cristals', models.IntegerField(default=1)),
                ('current_deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Deck')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.CardType'),
        ),
    ]
