# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-01 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monstercard',
            name='health',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monstercard',
            name='strengh',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='health',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='mana_cristals',
            field=models.IntegerField(default=1),
        ),
    ]
