# Generated by Django 2.0 on 2017-12-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='effect',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='strengh',
            field=models.IntegerField(null=True),
        ),
    ]
