# Generated by Django 2.0 on 2017-12-07 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171207_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cards', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('health', models.IntegerField(default=30)),
                ('mana_cristals', models.IntegerField(default=1)),
                ('current_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Deck')),
            ],
        ),
    ]
