INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (1, 1, 'add_logentry', 'Can add log entry');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (2, 1, 'change_logentry', 'Can change log entry');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (3, 1, 'delete_logentry', 'Can delete log entry');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (4, 2, 'add_permission', 'Can add permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (5, 2, 'change_permission', 'Can change permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (6, 2, 'delete_permission', 'Can delete permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (7, 3, 'add_group', 'Can add group');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (8, 3, 'change_group', 'Can change group');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (9, 3, 'delete_group', 'Can delete group');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (10, 4, 'add_contenttype', 'Can add content type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (11, 4, 'change_contenttype', 'Can change content type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (12, 4, 'delete_contenttype', 'Can delete content type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (13, 5, 'add_session', 'Can add session');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (14, 5, 'change_session', 'Can change session');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (15, 5, 'delete_session', 'Can delete session');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (16, 6, 'add_user', 'Can add user');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (17, 6, 'change_user', 'Can change user');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (18, 6, 'delete_user', 'Can delete user');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (19, 7, 'add_card', 'Can add card');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (20, 7, 'change_card', 'Can change card');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (21, 7, 'delete_card', 'Can delete card');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (22, 8, 'add_cardtype', 'Can add card type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (23, 8, 'change_cardtype', 'Can change card type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (24, 8, 'delete_cardtype', 'Can delete card type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (25, 9, 'add_deck', 'Can add deck');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (26, 9, 'change_deck', 'Can change deck');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (27, 9, 'delete_deck', 'Can delete deck');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (28, 10, 'add_token', 'Can add Token');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (29, 10, 'change_token', 'Can change Token');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (30, 10, 'delete_token', 'Can delete Token');