INSERT INTO sqlite_sequence (name, seq) VALUES ('django_migrations', 19);
INSERT INTO sqlite_sequence (name, seq) VALUES ('django_content_type', 10);
INSERT INTO sqlite_sequence (name, seq) VALUES ('auth_permission', 30);
INSERT INTO sqlite_sequence (name, seq) VALUES ('django_admin_log', 8);
INSERT INTO sqlite_sequence (name, seq) VALUES ('app_user', 1);
INSERT INTO sqlite_sequence (name, seq) VALUES ('app_cardtype', 2);
INSERT INTO sqlite_sequence (name, seq) VALUES ('app_card', 2);
INSERT INTO sqlite_sequence (name, seq) VALUES ('app_deck', 1);
INSERT INTO sqlite_sequence (name, seq) VALUES ('app_deck_cards', 2);